title: Linda's Housing 
email: linda.auyeung@finance.nsw.gov.au
description: >- # this means to ignore newlines until "baseurl:"
  Linda's testing
baseurl: "/housing" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tjharrop
github_username:  tjharrop

browserTitle: NSW Gov prototyping demo - Linda's housing

stage: prototype

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

remote_theme: tjharrop/NSW-jekyll-theme
